table Products

	/// Number of products.
	measure 'Product Count' = ```
		DISTINCTCOUNT(Products[ProductID])
		```
		formatString: #,##0

	column ProductID
		dataType: int64
		sourceColumn: ProductID
		summarizeBy: none
		isKey
	column ProductName
		dataType: string
		sourceColumn: ProductName
		summarizeBy: none
	column Category
		dataType: string
		sourceColumn: Category
		summarizeBy: none
	column SubCategory
		dataType: string
		sourceColumn: SubCategory
		summarizeBy: none
	column UnitPrice
		dataType: decimal
		sourceColumn: UnitPrice
		summarizeBy: none
	column Cost
		dataType: decimal
		sourceColumn: Cost
		summarizeBy: none

	partition Products = m
		mode: import
		source =
			let
				// Load local CSV from project data folder
				Source = Csv.Document(File.Contents("D:/power_new/data/Products.csv"), [Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"ProductID", Int64.Type}, {"ProductName", type text}, {"Category", type text}, {"SubCategory", type text}, {"UnitPrice", type number}, {"Cost", type number}})
			in
				#"Changed Type"
		annotation PBI_ResultType = Table
